name: plbenchmark
channels:
  - conda-forge
dependencies:
    # Base depends
  - python
  - pip

    # Testing
  - pytest
  - pytest-cov
  - codecov
  - nbval
  - coverage

  - pyyaml
  - numpy
  - matplotlib
  - pandas
  - rdkit
  - networkx
  - openff-units
  - scipy
  - openff-toolkit
  - requests
  - git-lfs
  - nbsphinx     
